FROM golang:1.23.8 AS builder
WORKDIR /callisto
COPY . ./
RUN go mod download
RUN go build -mod=readonly -buildvcs=false -o build/callisto ./cmd/callisto

FROM golang
RUN useradd -ms /bin/bash callisto
WORKDIR /home/callisto
COPY --from=builder /callisto/build/callisto /usr/local/bin/callisto
COPY --chown=callisto:callisto mainnet-genesis.json /home/callisto/.callisto/genesis.json
COPY --chown=callisto:callisto start.sh /usr/local/bin/start
ENTRYPOINT [ "start" ]
USER callisto